<?php
/**
 * Class Me_Gravity_Block_Js_Gravity
 *
 * @category  Me
 * @package   Me_Gravity
 * @author    Attila Sági <sagi.attila@magevolve.com>
 * @copyright 2014 Magevolve Ltd. (http://magevolve.com)
 * @license   http://magevolve.com/terms-and-conditions Magevolve Ltd. License
 * @link      http://magevolve.com
 */
?>
<?php
/**
 * Gravity initialization script
 *
 * var $this Me_Gravity_Block_Page_Js_Gravity
 * @see Me_Gravity_Block_Page_Js_Gravity
 */
?>
<?php if ($this->isEnabled() && $this->getGravityCustomerId()) : ?>
    <?php $gravityHelper = $this->getGravityHelper(); ?>
    <?php if ($this->isCustomJsEnabled()) : ?>
        <?php echo $this->getCustomJsContent(); ?>
    <?php else : ?>
        <script type="text/javascript">
        //<![CDATA[
            <?php if ($gravityHelper->useBulkRecommendation() && $gravityHelper->useGravityTemplate()) : ?>
            window.gravityGroupSeq = 1;
            window.gravityGroupSize = 0;
            <?php endif; ?>
            var _gravity = _gravity || [];
            (function () {
                var gr = document.createElement("script");
                gr.type = "text/javascript";
                gr.async = !0;
                //gr.src = document.location.protocol + "//saas.gravityrd.com/js/CUSTOMERID/gr_reco4-min.js";
                gr.src = "http://<?php echo $this->getGravityCustomerId() ?>-bud.gravityrd-services.com/js/<?php echo $this->getGravityCustomerId() ?>/gr_reco4-min.js";
                var s = document.getElementsByTagName("script")[0];
                s.parentNode.insertBefore(gr, s);
            })();
        //]]>
        </script>
    <?php endif; ?>
<?php endif; ?>
