<?php
/**
 * Class Me_Gravity_Block_Recommendation
 *
 * @category  Me
 * @package   Me_Gravity
 * @author    Attila Sági <sagi.attila@magevolve.com>
 * @copyright 2015 Magevolve Ltd. (http://magevolve.com)
 * @license   http://magevolve.com/terms-and-conditions Magevolve Ltd. License
 * @link      http://magevolve.com
 */
?>
<?php
/**
 * @see Me_Gravity_Block_Recommendation
 */
?>
<?php $gravityHelper = $this->getGravityHelper(); ?>
<?php if ($gravityHelper->useGravityTemplate()) : ?>
    <?php $storeId = $this->getStoreId(); ?>
    <?php $_columnCount = 5; ?>
    <div class="box box-<?php echo $this->getBoxClass() ?>">
        <div class="box-head">
            <?php if($title = $this->getRecommendationTitle()) : ?>
                <h3><?php echo $title ?></h3>
            <?php else : ?>
                <h3><?php echo $gravityHelper->__('Recommended Item(s)') ?></h3>
            <?php endif; ?>
        </div>
        <div id="target-<?php echo $this->getBoxClass() ?>" class="box-content"><?php echo $gravityHelper->__('Recommendations will be displayed here') ?></div>
        <div id="template-<?php echo $this->getBoxClass() ?>" style="display: none;">
            <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col gravity-<?php echo $this->getBoxClass() ?>-grid">
                {for p in products}
                    <li class="item" style="min-height: 200px;">
                        <a class="product-image" href="${p.link_<?php echo $storeId ?>}" onmousedown="_gravity.push({ type: 'event', eventType: 'REC_CLICK', itemId: '${p.itemid}'});">
                            <img id="product-collection-image-${p.itemid}'}" src='${p.image_link_<?php echo $storeId ?>}' />
                        </a>
                        <div class="recItemTitle product-name">
                            <a class="recItemTitle product-name" href="${p.link_<?php echo $storeId ?>}" onmousedown="_gravity.push({type: 'event', eventType: 'REC_CLICK', itemId: '${p.itemid}'});">${p.title_<?php echo $storeId ?>}</a>
                        </div>
                    </li>
                {/for}
            </ul>
        </div>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        _gravity.push({
            type: "recommendation",
            scenarioId: "<?php echo $this->getRecommendationType() ?>",
            numberLimit: <?php echo $this->getRecommendationLimit() ?>,
            storeId: <?php echo $storeId ?>,
            <?php if($itemIds = $this->getCartItems()) : ?>
                <?php foreach($itemIds as $itemId) : ?>
                    cartItemId: "<?php echo $itemId ?>",
                <?php endforeach; ?>
            <?php endif; ?>
            resultNames: ["itemId", "title_<?php echo $storeId ?>", "link_<?php echo $storeId ?>", "image_link_<?php echo $storeId ?>"],
            templating: {
                targetElementId: "target-<?php echo $this->getBoxClass() ?>",
                templateElementId: "template-<?php echo $this->getBoxClass() ?>"
            }
        });
        //]]>
    </script>
<?php else : ?>
    <?php $items = $this->getProductCollection(); ?>
    <?php if (!is_null($items) && $items->count()) : ?>
        <div class="box box-<?php echo $this->getBoxClass() ?>">
            <div class="box-head">
                <?php if($title = $this->getRecommendationTitle()) : ?>
                    <h3><?php echo $title ?></h3>
                <?php else : ?>
                    <h3><?php echo $gravityHelper->__('Recommended Item(s)') ?></h3>
                <?php endif; ?>
            </div>
            <div class="box-content">
                <?php $_collectionSize = $items->count(); ?>
                <?php $_columnCount = $this->getBoxColumnCount(); ?>
                <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col gravity-<?php echo $this->getBoxClass() ?>-grid">
                <?php $i = 0; foreach ($items as $_product): ?>
                    <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" onmousedown="_gravity.push({ type: 'event', eventType: 'REC_CLICK', recId: '<?php echo $this->getRecommendationId() ?>', itemId: '<?php echo $_product->getId() ?>'});">
                            <?php $_imgSize = 210; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>
                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" onmousedown="_gravity.push({ type: 'event', eventType: 'REC_CLICK', recId: '<?php echo $this->getRecommendationId() ?>', itemId: '<?php echo $_product->getId() ?>'});"><?php echo $this->stripTags($_product->getName(), null, true) ?></a></h3>
                        <?php echo $this->getPriceHtml($_product, true, '-' . $this->getBoxClass()) ?>
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    </li>
                <?php endforeach; ?>
                </ul>
                <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>